/*
This is brutally ugly, but until https://github.com/square/dagger/issues/410 is resolved,
this is the best I can do while making sure that I can refactor the API later.
 */
//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package org.bspeice.minimalbible.activities.downloader;

import android.content.Context;
import android.content.SharedPreferences;

import org.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import org.androidannotations.api.sharedpreferences.BooleanPrefField;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.LongPrefEditorField;
import org.androidannotations.api.sharedpreferences.LongPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;

public final class DownloadPrefs_
    extends SharedPreferencesHelper
{

    private Context context_;

    public DownloadPrefs_(Context context) {
        super(context.getSharedPreferences("DownloadPrefs", 0));
        this.context_ = context;
    }

    public DownloadPrefs_.DownloadPrefsEditor_ edit() {
        return new DownloadPrefs_.DownloadPrefsEditor_(getSharedPreferences());
    }

    public BooleanPrefField hasEnabledDownload() {
        return booleanField("hasEnabledDownload", false);
    }

    public BooleanPrefField showedDownloadDialog() {
        return booleanField("showedDownloadDialog", false);
    }

    public LongPrefField downloadRefreshedOn() {
        return longField("downloadRefreshedOn", 0L);
    }

    public final static class DownloadPrefsEditor_
        extends EditorHelper<DownloadPrefs_.DownloadPrefsEditor_>
    {


        DownloadPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public BooleanPrefEditorField<DownloadPrefs_.DownloadPrefsEditor_> hasEnabledDownload() {
            return booleanField("hasEnabledDownload");
        }

        public BooleanPrefEditorField<DownloadPrefs_.DownloadPrefsEditor_> showedDownloadDialog() {
            return booleanField("showedDownloadDialog");
        }

        public LongPrefEditorField<DownloadPrefs_.DownloadPrefsEditor_> downloadRefreshedOn() {
            return longField("downloadRefreshedOn");
        }

    }

}
